CREATE TABLE IF NOT EXISTS ProfileRestriction (
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  profileId TEXT, 
  suspended INTEGER DEFAULT 0, 
  limited INTEGER DEFAULT 0, 
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  updatedAt TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Verified (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    profileId TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_profileId ON Verified (profileId);
CREATE INDEX IF NOT EXISTS idx_profileId ON ProfileRestriction (profileId);

ALTER TABLE ProfileRestriction
ADD COLUMN flagged INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS AllowedToken (
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  name TEXT,
  symbol TEXT,
  decimals INTEGER DEFAULT 18,
  address TEXT UNIQUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
